let token=localStorage.getItem('hv_admin_token')||'',data=null,editingProductId=null;
const login=document.querySelector('#login'),app=document.querySelector('#adminApp');
async function req(url,opt={}){opt.headers={...(opt.headers||{}),Authorization:`Bearer ${token}`};if(!(opt.body instanceof FormData))opt.headers['Content-Type']='application/json';const r=await fetch(HV.api(url),opt),d=await r.json();if(r.status===401){logout();throw new Error('Sessão expirada.')}if(!r.ok)throw new Error(d.message||'Erro');return d}
const val=id=>document.querySelector('#'+id).value;
function orderProfit(o){return Number(o.estimatedProfit??o.total??0)}
async function load(){data=await req('/api/admin/dashboard');document.querySelector('#stProducts').textContent=data.products.length;document.querySelector('#stCoupons').textContent=data.coupons.length;document.querySelector('#stOrders').textContent=data.orders.length;document.querySelector('#stActive').textContent=data.products.filter(p=>p.active!==false).length;
const approved=data.orders.filter(o=>String(o.paymentStatus||'').startsWith('approved'));const revenue=approved.reduce((s,o)=>s+Number(o.total||0),0),profit=approved.reduce((s,o)=>s+orderProfit(o),0);
document.querySelector('#stRevenue').textContent=HV.money(revenue);document.querySelector('#stProfit').textContent=HV.money(profit);document.querySelector('#stSales').textContent=approved.length;renderProducts();renderCoupons();renderOrders()}
function renderProducts(){const rows=document.querySelector('#productRows');rows.innerHTML=data.products.length?data.products.map(p=>`<tr><td><div class="admin-product-cell">${p.image?`<img src="${HV.media(p.image)}" alt="">`:`<span>${p.icon||'◆'}</span>`}<div><b>${p.name}</b><br><small class="muted">${p.description||''}</small>${p.bonus?`<br><small class="bonus-text">Bônus: ${p.bonus}</small>`:''}</div></div></td><td>${p.category}</td><td>${HV.money(p.price)}</td><td>${p.exclusive?'SIM':'—'}</td><td>${p.limited?'SIM':'—'}</td><td>${p.limited?(Number(p.stock)||0):'∞'}</td><td><span class="status ${p.active!==false?'on':'off'}">${p.active!==false?'ATIVO':'PAUSADO'}</span></td><td><button class="btn ghost edit-product" data-id="${p.id}">Editar</button> <button class="btn ghost toggle-product" data-id="${p.id}">${p.active!==false?'Pausar':'Ativar'}</button> <button class="btn ghost del-product" data-id="${p.id}">Excluir</button></td></tr>`).join(''):'<tr><td colspan="8">Nenhum produto.</td></tr>';
document.querySelectorAll('.edit-product').forEach(b=>b.onclick=()=>startEditProduct(b.dataset.id));document.querySelectorAll('.toggle-product').forEach(b=>b.onclick=async()=>{const p=data.products.find(x=>x.id===b.dataset.id);await req(`/api/admin/products/${encodeURIComponent(p.id)}`,{method:'PUT',body:JSON.stringify({...p,active:!(p.active!==false)})});HV.toast('Produto atualizado.');load()});document.querySelectorAll('.del-product').forEach(b=>b.onclick=async()=>{if(!confirm('Excluir este produto da loja?'))return;await req(`/api/admin/products/${encodeURIComponent(b.dataset.id)}`,{method:'DELETE'});HV.toast('Produto excluído.');load()})}
function productPayload(){return {name:val('pName'),price:Number(val('pPrice')),costPrice:Number(val('pCostPrice')||0),category:val('pCategory'),badge:val('pBadge'),icon:val('pIcon'),description:val('pDescription'),active:val('pActive')==='true',exclusive:val('pExclusive')==='true',bonus:val('pBonus'),limited:val('pLimited')==='true',stock:Math.max(0,Number(val('pStock')||0)),image:val('pImage')}}
function setPreview(src){src=HV.media(src);const box=document.querySelector('#imagePreview');box.innerHTML=src?`<img src="${src}" alt="Prévia do produto">`:'<span>Prévia da imagem</span>'}
function clearProductForm(){editingProductId=null;['pName','pPrice','pCostPrice','pBadge','pIcon','pDescription','pBonus','pImage'].forEach(id=>document.querySelector('#'+id).value='');document.querySelector('#pImageFile').value='';document.querySelector('#pStock').value='0';document.querySelector('#pCategory').value='VIPs';document.querySelector('#pActive').value='true';document.querySelector('#pExclusive').value='false';document.querySelector('#pLimited').value='false';document.querySelector('#productFormTitle').textContent='Adicionar item à loja';document.querySelector('#saveProduct').textContent='Adicionar produto';document.querySelector('#cancelProductEdit').classList.add('hidden');setPreview('')}
function startEditProduct(id){const p=data.products.find(x=>x.id===id);if(!p)return;editingProductId=id;document.querySelector('#pName').value=p.name;document.querySelector('#pPrice').value=p.price;document.querySelector('#pCostPrice').value=p.costPrice||0;document.querySelector('#pCategory').value=p.category;document.querySelector('#pBadge').value=p.badge||'';document.querySelector('#pIcon').value=p.icon||'';document.querySelector('#pDescription').value=p.description||'';document.querySelector('#pActive').value=String(p.active!==false);document.querySelector('#pExclusive').value=String(!!p.exclusive);document.querySelector('#pBonus').value=p.bonus||'';document.querySelector('#pLimited').value=String(!!p.limited);document.querySelector('#pStock').value=Number(p.stock)||0;document.querySelector('#pImage').value=p.image||'';document.querySelector('#pImageFile').value='';setPreview(HV.media(p.image||''));document.querySelector('#productFormTitle').textContent='Editar produto';document.querySelector('#saveProduct').textContent='Salvar alterações';document.querySelector('#cancelProductEdit').classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}
function renderCoupons(){document.querySelector('#couponRows').innerHTML=data.coupons.map(c=>`<tr><td><b>${c.code}</b></td><td>${c.discount}%</td><td>${c.uses||0}${c.maxUses?` / ${c.maxUses}`:' / ∞'}</td><td>${c.expiresAt||'Sem limite'}</td><td><span class="status ${c.active?'on':'off'}">${c.active?'ATIVO':'PAUSADO'}</span></td><td><button class="btn ghost toggle" data-code="${c.code}" data-active="${c.active}">${c.active?'Pausar':'Ativar'}</button> <button class="btn ghost del" data-code="${c.code}">Excluir</button></td></tr>`).join('');document.querySelectorAll('.toggle').forEach(b=>b.onclick=async()=>{const c=data.coupons.find(x=>x.code===b.dataset.code);await req(`/api/admin/coupons/${encodeURIComponent(c.code)}`,{method:'PUT',body:JSON.stringify({...c,active:!c.active})});HV.toast('Cupom atualizado.');load()});document.querySelectorAll('.del').forEach(b=>b.onclick=async()=>{if(!confirm(`Excluir o cupom ${b.dataset.code}?`))return;await req(`/api/admin/coupons/${encodeURIComponent(b.dataset.code)}`,{method:'DELETE'});HV.toast('Cupom excluído.');load()})}
function renderOrders(){document.querySelector('#orderRows').innerHTML=data.orders.length?data.orders.map(o=>`<tr><td><b>${o.id}</b></td><td>${o.account}</td><td>${HV.money(o.total)}</td><td>${HV.money(orderProfit(o))}</td><td>${o.paymentStatus}</td><td>${o.deliveryStatus}</td><td>${new Date(o.createdAt).toLocaleString('pt-BR')}</td></tr>`).join(''):'<tr><td colspan="7">Nenhum pedido ainda.</td></tr>'}
function show(){login.classList.add('hidden');app.classList.remove('hidden');load().catch(e=>HV.toast(e.message))}function logout(){token='';localStorage.removeItem('hv_admin_token');app.classList.add('hidden');login.classList.remove('hidden')}
document.querySelector('#loginBtn').onclick=async()=>{const password=val('password');try{const r=await fetch(HV.api('/api/admin/login'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})}),d=await r.json();if(!r.ok)throw new Error(d.message);token=d.token;localStorage.setItem('hv_admin_token',token);show()}catch(e){document.querySelector('#loginMsg').textContent=e.message}};
document.querySelector('#logout').onclick=logout;
document.querySelector('#createCoupon').onclick=async()=>{try{await req('/api/admin/coupons',{method:'POST',body:JSON.stringify({code:val('cCode'),discount:Number(val('cDiscount')),maxUses:Number(val('cMax')),expiresAt:val('cExp'),active:true})});document.querySelector('#cCode').value='';HV.toast('Cupom criado.');load()}catch(e){HV.toast(e.message)}};
document.querySelector('#uploadProductImage').onclick=async()=>{const file=document.querySelector('#pImageFile').files[0];if(!file)return HV.toast('Escolha uma imagem primeiro.');if(file.size>5*1024*1024)return HV.toast('A imagem deve ter no máximo 5 MB.');if(!/^image\/(png|jpeg|webp|gif)$/.test(file.type))return HV.toast('Formato de imagem não aceito.');const reader=new FileReader();reader.onload=async()=>{try{const d=await req('/api/admin/upload-image',{method:'POST',body:JSON.stringify({name:file.name,type:file.type,data:reader.result})});document.querySelector('#pImage').value=d.path;setPreview(HV.media(d.path));HV.toast('Imagem enviada. Agora salve o produto.')}catch(e){HV.toast(e.message)}};reader.readAsDataURL(file)};
document.querySelector('#clearProductImage').onclick=()=>{document.querySelector('#pImage').value='';document.querySelector('#pImageFile').value='';setPreview('')};
document.querySelector('#saveProduct').onclick=async()=>{try{const payload=productPayload();if(editingProductId){await req(`/api/admin/products/${encodeURIComponent(editingProductId)}`,{method:'PUT',body:JSON.stringify(payload)});HV.toast('Produto salvo.')}else{await req('/api/admin/products',{method:'POST',body:JSON.stringify(payload)});HV.toast('Produto adicionado à loja.')}clearProductForm();load()}catch(e){HV.toast(e.message)}};
document.querySelector('#cancelProductEdit').onclick=clearProductForm;
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{['dashboard','products','coupons','orders','licenses'].forEach(v=>document.querySelector(`#${v}View`).classList.toggle('hidden',v!==b.dataset.view));document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active-side',x===b))});
let licenses=[];
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fmtDate(v){if(!v)return 'Nunca';try{return new Date(v).toLocaleString('pt-BR')}catch{return String(v)}}
async function loadLicenses(){try{const d=await req('/api/admin/licenses');licenses=d.licenses||[];renderLicenses()}catch(e){document.querySelector('#licenseRows').innerHTML=`<tr><td colspan="7">${esc(e.message)}</td></tr>`}}
function renderLicenses(){const rows=document.querySelector('#licenseRows');rows.innerHTML=licenses.length?licenses.map(l=>`<tr><td><b>${esc(l.display_name||l.resource_id)}</b><br><small class="muted">Chave ${esc(l.license_key_hint||'—')} • v${Number(l.key_version||1)}</small></td><td><code>${esc(l.resource_id)}</code></td><td><span class="status ${l.active?'on':'off'}">${l.active?'ATIVA':'REVOGADA'}</span></td><td>${esc(l.server_name||'—')}</td><td><small>IP: ${esc(l.allowed_ip||'—')}<br>Porta: ${esc(l.allowed_port||'—')}<br>Instância: ${esc(l.allowed_instance_id||'—')}</small></td><td>${fmtDate(l.last_validation_at)}</td><td><button class="btn ghost lic-toggle" data-id="${esc(l.resource_id)}" data-active="${l.active}">${l.active?'Revogar':'Ativar'}</button> <button class="btn ghost lic-bind" data-id="${esc(l.resource_id)}">Servidor</button> <button class="btn ghost lic-rotate" data-id="${esc(l.resource_id)}">Nova chave</button> <button class="btn ghost lic-clear" data-id="${esc(l.resource_id)}">Desvincular</button></td></tr>`).join(''):'<tr><td colspan="7">Nenhuma licença cadastrada.</td></tr>';
document.querySelectorAll('.lic-toggle').forEach(b=>b.onclick=async()=>{try{await req('/api/admin/licenses/'+encodeURIComponent(b.dataset.id),{method:'PATCH',body:JSON.stringify({active:b.dataset.active!=='true'})});HV.toast(b.dataset.active==='true'?'Licença revogada.':'Licença ativada.');loadLicenses()}catch(e){HV.toast(e.message)}});
document.querySelectorAll('.lic-rotate').forEach(b=>b.onclick=async()=>{if(!confirm('Gerar uma nova chave? A chave antiga deixará de funcionar imediatamente.'))return;try{const d=await req('/api/admin/licenses/'+encodeURIComponent(b.dataset.id)+'/rotate',{method:'POST',body:'{}'});showNewKey(d.license_key,b.dataset.id);loadLicenses()}catch(e){HV.toast(e.message)}});
document.querySelectorAll('.lic-clear').forEach(b=>b.onclick=async()=>{if(!confirm('Remover IP, porta e Instance ID autorizados deste mod?'))return;try{await req('/api/admin/licenses/'+encodeURIComponent(b.dataset.id)+'/clear-binding',{method:'POST',body:'{}'});HV.toast('Vínculo removido.');loadLicenses()}catch(e){HV.toast(e.message)}});
document.querySelectorAll('.lic-bind').forEach(b=>b.onclick=async()=>{const l=licenses.find(x=>x.resource_id===b.dataset.id);const ip=prompt('IP autorizado:',l?.allowed_ip||'');if(ip===null)return;const port=prompt('Porta autorizada:',l?.allowed_port||'22321');if(port===null)return;const instance=prompt('Instance ID:',l?.allowed_instance_id||'horizonville-production-01');if(instance===null)return;const server=prompt('Nome do servidor:',l?.server_name||'Horizonville Roleplay');if(server===null)return;try{await req('/api/admin/licenses/'+encodeURIComponent(b.dataset.id),{method:'PATCH',body:JSON.stringify({allowed_ip:ip.trim()||null,allowed_port:port.trim()?Number(port):null,allowed_instance_id:instance.trim()||null,server_name:server.trim()||null})});HV.toast('Servidor atualizado.');loadLicenses()}catch(e){HV.toast(e.message)}})}
function showNewKey(key,id){const box=document.querySelector('#newLicenseKey');box.classList.remove('hidden');box.innerHTML=`<b>Nova chave de ${esc(id)}</b><br><code>${esc(key||'')}</code><br><small>Copie agora. Por segurança, a API não mostra a chave completa novamente.</small>`;window.scrollTo({top:box.offsetTop-120,behavior:'smooth'})}
document.querySelector('#refreshLicenses').onclick=loadLicenses;
document.querySelector('#createLicense').onclick=async()=>{const resource=val('lResource').trim();if(!resource)return HV.toast('Informe o nome da pasta/resource.');try{const d=await req('/api/admin/licenses',{method:'POST',body:JSON.stringify({resource_id:resource,display_name:val('lName').trim()||resource,allowed_ip:val('lIp').trim()||null,allowed_port:val('lPort')?Number(val('lPort')):null,allowed_instance_id:val('lInstance').trim()||null,server_name:val('lServer').trim()||null})});showNewKey(d.license_key,resource);HV.toast('Licença criada.');loadLicenses()}catch(e){HV.toast(e.message)}};
document.querySelector('[data-view="licenses"]').addEventListener('click',loadLicenses);

if(token)show();