let botToken=sessionStorage.getItem('hv_bot_panel_token')||'',botData=null;
const q=s=>document.querySelector(s), bool=v=>String(v)==='true', val=id=>q('#'+id).value, esc=v=>HV.escape(v);
async function breq(path,opt={}){opt.headers={...(opt.headers||{}),Authorization:`Bearer ${botToken}`};if(opt.json!==undefined){opt.headers['Content-Type']='text/plain;charset=UTF-8';opt.body=JSON.stringify(opt.json);delete opt.json}const r=await fetch(HV.api(path),opt),text=await r.text();let d={};try{d=text?JSON.parse(text):{}}catch{d={message:text}}if(r.status===401){lockBot();throw new Error(d.message||'Sessão expirada.')}if(!r.ok)throw new Error(d.message||'Erro');return d}
function lockBot(){botToken='';sessionStorage.removeItem('hv_bot_panel_token');q('#botApp').classList.add('hidden');q('#botLogin').classList.remove('hidden');initLogin()}
async function initLogin(){const me=await HV.me(true),st=q('#botDiscordState'),btn=q('#botUnlock'),connect=q('#botDiscordLogin');if(!me){st.textContent='❌ Conecte seu Discord para continuar.';connect.classList.remove('hidden');btn.disabled=true;return null}connect.classList.add('hidden');if(!me.access?.bot){st.textContent=`⛔ ${me.user.displayName||me.user.username}, seu Discord não possui acesso ao Painel do Bot.`;btn.disabled=true;return me}st.textContent=`✅ Discord autorizado: ${me.user.displayName||me.user.username} (${me.user.discordId})`;btn.disabled=false;return me}
q('#botDiscordLogin').onclick=()=>HV.login('/hv-bot-panel');q('#botUnlock').onclick=async()=>{try{const d=await HV.request('/api/panel/bot/unlock',{method:'POST',json:{password:val('botPassword')},auth:true});botToken=d.token;sessionStorage.setItem('hv_bot_panel_token',botToken);openBot()}catch(e){q('#botLoginMsg').textContent=e.message}};q('#botLogout').onclick=lockBot;
async function openBot(){q('#botLogin').classList.add('hidden');q('#botApp').classList.remove('hidden');await loadConfig()}
async function loadConfig(){botData=await breq('/api/bot-panel/config');const s=botData.settings,w=s.welcome,st=s.serverStatus,a=s.allowlist;q('#botRevision').textContent='#'+botData.revision;q('#mtaState').textContent=botData.serverStatus?.online?'🟢 ONLINE':'🔴 OFFLINE';q('#mtaPlayers').textContent=`${botData.serverStatus?.players||0}/${botData.serverStatus?.maxPlayers||0} jogadores`;q('#allowlistState').textContent=a.enabled?(a.approvalMode==='staff'?'STAFF':'AUTO'):'OFF';q('#shopLogState').textContent=s.purchaseLogs?.enabled?'ON':'OFF';
[['wEnabled',w.enabled],['wChannel',w.channelId],['wTitle',w.title],['wDescription',w.description],['wColor',w.color],['wFooter',w.footer],['wImage',w.image||''],['wAvatar',w.showAvatar],['sEnabled',st.enabled],['sChannel',st.channelId],['sTitle',st.title],['sConnect',st.connectUrl],['sDescription',st.description],['sButton',st.buttonLabel],['sImage',st.image],['sColorOnline',st.colorOnline],['sColorOffline',st.colorOffline],['aEnabled',a.enabled],['aMode',a.approvalMode],['aPanelChannel',a.panelChannelId],['aTicketCategory',a.ticketCategoryId],['aApprovedChannel',a.approvedChannelId],['aStaffChannel',a.staffReviewChannelId],['aStaffRoles',(a.staffRoleIds||[]).join(',')],['aApprovedRole',a.approvedRoleId||''],['aColor',a.color||'#5865F2'],['aMin',a.minScore],['aCount',a.questionCount],['aClose',a.closeSeconds],['aTitle',a.title],['aDescription',a.description],['aButton',a.buttonLabel],['aEmoji',a.buttonEmoji],['purchaseLogChannel',s.purchaseLogs?.channelId||'']].forEach(([id,v])=>{if(q('#'+id))q('#'+id).value=String(v??'')});renderQuestions();renderCommands();q('#legacySettings').value=JSON.stringify(botData.legacySettings||{},null,2)}
function renderQuestions(){const a=botData.settings.allowlist,box=q('#questionEditors');box.innerHTML=(a.questions||[]).slice(0,10).map((x,i)=>`<div class="question-editor" data-q="${i}"><b>Pergunta ${i+1}</b><div class="field"><label>Enunciado</label><input class="qe-question" value="${esc(x.question)}"></div><div class="question-options">${(x.options||['','','','']).map((o,j)=>`<div class="field"><label>${String.fromCharCode(65+j)}</label><input class="qe-option" data-o="${j}" value="${esc(o)}"></div>`).join('')}</div><div class="field"><label>Resposta correta</label><select class="qe-correct"><option value="0" ${x.correctIndex==0?'selected':''}>A</option><option value="1" ${x.correctIndex==1?'selected':''}>B</option><option value="2" ${x.correctIndex==2?'selected':''}>C</option><option value="3" ${x.correctIndex==3?'selected':''}>D</option></select></div></div>`).join('')}
function collectQuestions(){return [...document.querySelectorAll('.question-editor')].map((el,i)=>({id:`q${i+1}`,question:el.querySelector('.qe-question').value.trim(),options:[...el.querySelectorAll('.qe-option')].map(x=>x.value.trim()),correctIndex:Number(el.querySelector('.qe-correct').value),enabled:true}))}
function renderCommands(){const c=botData.settings.commands||{};q('#commandToggles').innerHTML=Object.entries(c).map(([k,v])=>`<div class="field"><label>/${esc(k)}</label><select data-command="${esc(k)}"><option value="true" ${v?'selected':''}>Ativo</option><option value="false" ${!v?'selected':''}>Desativado</option></select></div>`).join('')}
async function savePatch(patch,msg='Configuração salva.'){await breq('/api/bot-panel/config',{method:'PUT',json:{settings:patch}});HV.toast(msg);await loadConfig()}
document.querySelectorAll('.save-section').forEach(b=>b.onclick=async()=>{try{if(b.dataset.section==='welcome')await savePatch({welcome:{...botData.settings.welcome,enabled:bool(val('wEnabled')),channelId:val('wChannel').trim(),title:val('wTitle'),description:val('wDescription'),color:val('wColor'),footer:val('wFooter'),image:val('wImage'),showAvatar:bool(val('wAvatar'))}});if(b.dataset.section==='serverStatus')await savePatch({serverStatus:{...botData.settings.serverStatus,enabled:bool(val('sEnabled')),channelId:val('sChannel').trim(),title:val('sTitle'),connectUrl:val('sConnect'),description:val('sDescription'),buttonLabel:val('sButton'),image:val('sImage'),colorOnline:val('sColorOnline'),colorOffline:val('sColorOffline')}});if(b.dataset.section==='allowlist')await savePatch({allowlist:{...botData.settings.allowlist,enabled:bool(val('aEnabled')),approvalMode:val('aMode'),panelChannelId:val('aPanelChannel').trim(),ticketCategoryId:val('aTicketCategory').trim(),approvedChannelId:val('aApprovedChannel').trim(),staffReviewChannelId:val('aStaffChannel').trim(),staffRoleIds:val('aStaffRoles').split(',').map(x=>x.trim()).filter(Boolean),approvedRoleId:val('aApprovedRole').trim(),color:val('aColor'),minScore:Number(val('aMin')||8),questionCount:Number(val('aCount')||10),closeSeconds:Number(val('aClose')||5),title:val('aTitle'),description:val('aDescription'),buttonLabel:val('aButton'),buttonEmoji:val('aEmoji')}})}catch(e){HV.toast(e.message)}});
q('#saveQuestions').onclick=async()=>{try{const questions=collectQuestions();if(questions.some(x=>!x.question||x.options.some(o=>!o)))return HV.toast('Preencha todas as perguntas e alternativas.');await savePatch({allowlist:{...botData.settings.allowlist,questions}},'Perguntas salvas.')}catch(e){HV.toast(e.message)}};
q('#saveCommands').onclick=async()=>{try{const commands={};document.querySelectorAll('[data-command]').forEach(x=>commands[x.dataset.command]=bool(x.value));await savePatch({commands,purchaseLogs:{...botData.settings.purchaseLogs,enabled:true,channelId:val('purchaseLogChannel').trim()}},'Comandos e logs salvos.')}catch(e){HV.toast(e.message)}};
q('#saveLegacy').onclick=async()=>{try{const legacySettings=JSON.parse(val('legacySettings'));await breq('/api/bot-panel/config',{method:'PUT',json:{legacySettings}});HV.toast('Tickets/denúncias sincronizados.');await loadConfig()}catch(e){HV.toast(e instanceof SyntaxError?'JSON inválido.':e.message)}};
async function action(type,channelId){const d=await breq('/api/bot-panel/actions',{method:'POST',json:{type,channelId}});HV.toast('Ação enviada ao bot. Aguarde alguns segundos.');return d}q('#publishStatus').onclick=()=>action('publish_status',val('sChannel')).catch(e=>HV.toast(e.message));q('#publishAllowlist').onclick=()=>action('publish_allowlist',val('aPanelChannel')).catch(e=>HV.toast(e.message));q('#loadAttempts').onclick=async()=>{try{const d=await breq('/api/bot-panel/allowlist/attempts');q('#allowlistResults').innerHTML=`<table class="table"><thead><tr><th>Discord</th><th>Nota</th><th>Status</th><th>Data</th></tr></thead><tbody>${(d.attempts||[]).map(a=>`<tr><td><code>${esc(a.discordId)}</code></td><td>${a.score}/${(a.answers||[]).length||botData.settings.allowlist.questionCount}</td><td>${esc(a.status)}</td><td>${new Date(a.createdAt).toLocaleString('pt-BR')}</td></tr>`).join('')||'<tr><td colspan="4">Nenhuma prova ainda.</td></tr>'}</tbody></table>`}catch(e){HV.toast(e.message)}};
document.querySelectorAll('[data-bot-view]').forEach(b=>b.onclick=()=>{['overview','welcome','status','allowlist','questions','commands','advanced'].forEach(v=>q('#'+v+'View')?.classList.toggle('hidden',v!==b.dataset.botView));document.querySelectorAll('[data-bot-view]').forEach(x=>x.classList.toggle('active-side',x===b))});
(async()=>{const me=await initLogin();if(botToken&&me?.access?.bot){try{await breq('/api/bot-panel/config');openBot()}catch{lockBot()}}})();
